set_property PACKAGE_PIN D18 [get_ports {gray_count[3]}]
set_property PACKAGE_PIN G14 [get_ports {gray_count[2]}]
set_property PACKAGE_PIN M15 [get_ports {gray_count[1]}]
set_property PACKAGE_PIN M14 [get_ports {gray_count[0]}]
set_property PACKAGE_PIN G15 [get_ports {en}]